version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zk0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    
  
  kafka1: 
    image: bitnami/kafka
    platform: linux/arm64
    container_name: kafka1
    depends_on:
      - zookeeper
    ports: 
      - 9092:9092  
      - 29092:29092
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 19000000
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk0:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  

  kafkaui:
    image: provectuslabs/kafka-ui
    container_name: kafkaui
    ports:
      - 8010:8080
    depends_on:
      - kafka1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zk0:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997

  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0-arm64
    container_name: elasticsearch
    platform: linux/arm64
    mem_limit: 5g
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.ml.enabled: false
      ES_JAVA_OPTS: -Xms3g -Xmx3g
    
  

  # schema-registry:
  #   image: confluentinc/cp-schema-registry
  #   container_name: schema1
  #   platform: linux/arm64/v8
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  #   ports:
  #     - 8081:8081
  


  kafka-connect:
    image: confluentinc/cp-kafka-connect-base:7.6.0-1-ubi8.arm64
    container_name: connect
    platform: linux/arm64
    ports: 
      - 8083:8083
    volumes:
      - ./connectPlugins:/usr/share/local-connectors
    environment:
      CONNECT_GROUP_ID: 1
      CONNECT_CONFIG_STORAGE_TOPIC: connect_config_storage
      CONNECT_OFFSET_STORAGE_TOPIC: connect_offset_storage
      CONNECT_STATUS_STORAGE_TOPIC: connect_status_storage
      CONNECT_BOOTSTRAP_SERVERS: kafka1:9092
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/usr/share/local-connectors" 


      




