version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-arm64
    container_name: elasticsearch
    mem_limit: 6g
    platform: linux/arm64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.ml.enabled: false
      ES_JAVA_OPTS: -Xms128m -Xmx512m
      xpack.security.http.ssl.enabled: true
      xpack.security.enrollment.enabled: true
      xpack.security.http.ssl.certificate: 


  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2-arm64
    container_name: kibana
    platform: linux/arm64
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    

    