version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0-arm64
    container_name: elasticsearch
    mem_limit: 6g
    platform: linux/arm64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.ml.enabled: false
      ES_JAVA_OPTS: -Xms3g -Xmx3g
    